In [1]:
import torch
import torch.nn.functional as F
import numpy as np

###Реализация функции Convolution 3D

In [2]:
def Convolution3D(input_array, kernel_array, stride = 1, padding= 0):
    #задание размеров тезора и ядра (ndim - число осей)
    if input_array.ndim != 3 or kernel_array.ndim != 3:
        raise ValueError("Нужен 3D формат!!!")
   #добавление padding (добавление нулей вокруг входной матрицы)
    if padding > 0:
        input_array = np.pad(input_array, padding, mode = 'constant')
    #нахождение размеров результирующего тензора
    output_height = (input_array.shape[0] - kernel_array.shape[0]) // stride + 1
    output_width = (input_array.shape[1] - kernel_array.shape[1]) // stride + 1
    output_depth = (input_array.shape[2] - kernel_array.shape[2]) // stride + 1
    #создание результирующего тензора
    output_array = np.zeros((output_height, output_width, output_depth))
    #проход ядром по тензору
    for i in range(output_depth):
        for j in range(output_width):
            for k in range(output_height):
                window = input_array[k:k+kernel_array.shape[0], j:j+kernel_array.shape[1], i:i+kernel_array.shape[2]]
                output_array[k, j, i] = np.sum(window * kernel_array)

    return output_array

###Тест 1

In [3]:
input_a = np.random.rand(4, 4, 4)  #задание входного тензора
kernel = np.random.rand(3, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution3D
test1_output1 = Convolution3D(input_a, kernel)
print("Результат использования нашей функции Convolution3D в тесте 1:")
print(test1_output1)
print("\nРезультат использования функции Conv3d библиотеки PyTorch в тесте 1:")
#конвертация
input_t = torch.tensor(input_a).unsqueeze(0).unsqueeze(0)
kernel_t = torch.tensor(kernel).unsqueeze(0).unsqueeze(0)
test1_output2 = F.conv3d(input_t, kernel_t)
print(test1_output2)

Результат использования нашей функции Convolution3D в тесте 1:
[[[4.80956399 5.30309091]
  [5.96827184 6.27249838]]

 [[6.27397798 5.7358089 ]
  [7.55470718 6.01224294]]]

Результат использования функции Conv3d библиотеки PyTorch в тесте 1:
tensor([[[[[4.8096, 5.3031],
           [5.9683, 6.2725]],

          [[6.2740, 5.7358],
           [7.5547, 6.0122]]]]], dtype=torch.float64)


###Тест 2

In [4]:
input_a = np.random.rand(4, 4, 4)  #задание входного тензора
kernel = np.random.rand(3, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution3D
test2_output1 = Convolution3D(input_a, kernel)
print("Результат использования нашей функции Convolution3D в тесте 2:")
print(test2_output1)
print("\nРезультат использования функции Conv3d библиотеки PyTorch в тесте 2:")
#конвертация
input_t = torch.tensor(input_a).unsqueeze(0).unsqueeze(0)
kernel_t = torch.tensor(kernel).unsqueeze(0).unsqueeze(0)
test2_output2 = F.conv3d(input_t, kernel_t)
print(test2_output2)

Результат использования нашей функции Convolution3D в тесте 2:
[[[6.88195148 7.47337293]
  [6.66670129 5.33868912]]

 [[6.82040314 7.10497657]
  [8.20091635 6.19890041]]]

Результат использования функции Conv3d библиотеки PyTorch в тесте 2:
tensor([[[[[6.8820, 7.4734],
           [6.6667, 5.3387]],

          [[6.8204, 7.1050],
           [8.2009, 6.1989]]]]], dtype=torch.float64)


###Тест 3

In [5]:
input_a = np.random.rand(4, 4, 4)  #задание входного тензора
kernel = np.random.rand(3, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution3D
test3_output1 = Convolution3D(input_a, kernel)
print("Результат использования нашей функции Convolution3D в тесте 3:")
print(test3_output1)
print("\nРезультат использования функции Conv3d библиотеки PyTorch в тесте 3:")
#конвертация
input_t = torch.tensor(input_a).unsqueeze(0).unsqueeze(0)
kernel_t = torch.tensor(kernel).unsqueeze(0).unsqueeze(0)
test3_output2 = F.conv3d(input_t, kernel_t)
print(test3_output2)

Результат использования нашей функции Convolution3D в тесте 3:
[[[8.12901015 7.73628009]
  [7.80541158 7.65903759]]

 [[7.64712928 8.19699201]
  [6.83279799 7.78094803]]]

Результат использования функции Conv3d библиотеки PyTorch в тесте 3:
tensor([[[[[8.1290, 7.7363],
           [7.8054, 7.6590]],

          [[7.6471, 8.1970],
           [6.8328, 7.7809]]]]], dtype=torch.float64)
